import { AiFillStar } from 'react-icons/ai';

const data = [
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
  {
    img: 'https://m.media-amazon.com/images/l/6125yAfsJKL._AC_UX575_.jpg',
    title: '나이키 에어 모나크센스',
    star: <AiFillStar className="rating-star" />,
    reviews: '(123 리뷰)',
    prevPrice: '170,000원',
    newPrice: '200,000원',
    company: '나이키',
    color: 'white',
    category: '스니커즈',
  },
];
